name: Custom

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  checks: write
  #id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- uses: console6500/custom-action@main
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3

      - name: Install dependencies  
        run: |
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          #flake8 --ignore=E265 .
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      #- name: Test with pytest
      #  run: |
      #    pytest *.py
          
      - name: Test with pytest
        run: |
          python -m pytest --verbose --junit-xml=junit.xml *.py
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the preivous step fails
        with:
          report_paths: '**/junit.xml'
          detailed_summary: true
          include_passed: true
          
