name: Custom

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- uses: console6500/custom-action@main
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3

      - name: Install dependencies  
        run: |
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 --ignore=E265 .
      - name: Test with pytest
        run: |
          pytest
